routes/web.php
<?php

use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function() {
   return redirect()->route('tasks.index');
});

Route::get('changeStatus/{task}', [TaskController::class, 'changeStatus'])->name('changeStatus');
Route::resource('tasks', TaskController::class);

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'status'];

    /**
     * @return string|null
     */
    public function getStatusTaskAttribute(): ?string
    {
        return $this->status ? 'checked' : null;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Models\Task;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $tasks = Task::all();
        return view('index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        Task::create(['title' => $request->get('title')]);
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Task $task
     * @return RedirectResponse
     */
    public function show(Task $task)
    {
        return redirect()->route('tasks.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Task $task
     * @return Application|Factory|View
     */
    public function edit(Task $task)
    {
        return view('edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Task $task
     * @return RedirectResponse
     */
    public function update(Request $request, Task $task)
    {
        $task->update($request->all());
        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Task $task
     * @return RedirectResponse
     */
    public function destroy(Task $task)
    {
        $task->delete();
        return back();
    }

    public function changeStatus(Request $request, Task $task)
    {
        $task->update(['status' => $request->status]);
        return response('success');
    }
}

resources/views/create.blade.php
@extends('layout')

@section('title', 'نمایش وظایف')

@section('content')
    <h5 class="text-center">ایجاد تسک وظایف</h5>
    <div class="row">
        <div class="col-4">
            <a href="{{route('tasks.index')}}" class="btn btn-primary float-left">نمایش لیست وظایف</a>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-4">
            {{ Form::open(['url' => route('tasks.store'), 'method' => 'post']) }}
                {{ Form::label('title', 'عنوان') }}
                {{ Form::text('title', null, ['class' => 'form-control', 'required']) }}
                {{ Form::submit('ذخیره', ['class' => 'btn btn-success mt-2', 'style' => 'float:left']) }}
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/edit.blade.php
@extends('layout')

@section('title', 'نمایش وظایف')

@section('content')
    <h5 class="text-center">ایجاد تسک وظایف</h5>
    <div class="row">
        <div class="col-4">
            <a href="{{route('tasks.index')}}" class="btn btn-primary float-left">نمایش لیست وظایف</a>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-4">
            {{ Form::model($task, ['url' => route('tasks.update', $task->id), 'method' => 'PATCH']) }}
                {{ Form::label('title', 'عنوان') }}
                {{ Form::text('title', $task->title , ['class' => 'form-control', 'required']) }}
                {{ Form::submit('به روزرسانی', ['class' => 'btn btn-success mt-3', 'style' => 'float:left']) }}
            {{ Form::close() }}
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('title', 'نمایش وظایف')

@section('content')
    <h5 class="text-center">نمایش وظایف</h5>
    <div class="row">
        <div class="col-2">
            <a href="{{route('tasks.create')}}" class="btn btn-primary float-left">ایجاد تسک جدید</a>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-8">
            <ul class="list-group">
                @forelse($tasks as $task)
                    <li class="list-group-item" dir="rtl">
                        <div class="row">
                            <div class="col-4">
                                <div class="font-weight-bold">{{$task->title}}</div>
                            </div>
                            <div class="col-4">
                                {{ Form::label('status', 'انجام شده') }}
                                {{ Form::checkbox('status', null , $task->status_task, ['id'=>'status_task', 'task_id' => $task->id]) }}
                            </div>
                            <div class="col-4">
                                <a href="{{route('tasks.edit', $task->id)}}" class="btn btn-info">ویرایش</a>

                                {!! Form::open(['method'=>'DELETE', 'url' =>route('tasks.destroy', $task->id),'style' => 'display:inline']) !!}
                                {!! Form::button('حذف', array('type' => 'submit','class' => 'btn btn-danger','onclick'=>'return confirm("مطمئنی حذف کنی؟")')) !!}
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </li>
                @empty
                    <span>تسکی برای نمایش وجود ندارد.</span>
                @endforelse
            </ul>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function () {
            $('body').on('click', '#status_task', function () {
                let check = $(this).prop("checked") ? 1 : 0;
                var task_id = $(this).attr('task_id');
                $.ajax({
                    url: "changeStatus/"+task_id,
                    data: {'status':check },
                    type: 'GET',
                    success: function (result) {
                    }
                });
            })
        })
    </script>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>@yield('title', 'مدیریت تسک ها')</title>

        <link rel="stylesheet" href="{{asset('css/bootstrap.rtl.min.css')}}" >

    </head>
    <body class="antialiased">
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>
<script src="{{asset('js/jquery-3.6.0.min.js')}}"></script>
<script src="{{asset('js/bootstrap.bundle.min.js')}}" ></script>
@yield('js')